# 기본정보
minimal_mistakes_skin: "dark" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise" 중에 원하는 스킨으로 선택한다.
locale: "en-US" # 언어 설정이며 ko-KR 로 설정하면 한국어로 바뀐다.
title: "KooYS blog" # 블로그 이름
subtitle: # 부제목으로, 블로그 이름 밑에 작게 표시된다.
name: "KooYS" # 이름
description: "KooYS 블로그" # 설명
url: "https://KooYS.github.io" # https://깃허브유저네임.github.io 형식으로 입력하면된다.
baseurl: "" # baseurl을 사용하고 있으면 입력하면된다.
teaser: # 연관포스트나 검색 등에서 미리보기 사진을 설정하고 싶으면 넣으면된다.
logo: # 블로그 타이틀 옆에 들어가는 로고

# disqus 댓글기능 활성화
comments:
  provider: "disqus"
  disqus:
    shortname: "KooYS"

# 블로그 검색기능 설정
search: true # true로 해야 활성화됨
search_full_content: true # 내용까지 검색되게 하려면 true

# 웹마스터 인증할때 쓰면된다.
google_site_verification:
naver_site_verification:

# 저자 설정
author:
  name: "KooYS"
  avatar: "https://avatars.githubusercontent.com/u/17160263?v=4" # 사진
  bio: "Developer."
  location: "Seoul"
  email: # 밑의 이메일과 이것중에 하나만 설정하면 된다.
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:koo@duckzill.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://KooYS.github.io/"
# Site Footer
footer:
  links:
    # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/KooYS"

# syntax 하이라이터 설정
highlighter: rouge

# 발췌 부분 뽑아내는 기준을 어떻게 정할건지
excerpt_separator: "\n\n"

# _posts와 _pages 불러오기
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: false
      related: false
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
