name: Build and Deploy
on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1
              with:
                  persist-credentials: false

            - name: Install and Build
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - run: yarn install
            - run: yarn export
            - run: touch out/.nojekyll

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: page
                  FOLDER: out
                  CLEAN: true
